import type { Transition } from "framer-motion";

export const transition: Transition = {
  duration: 10,
  repeat: Infinity,
  repeatType: "loop" as const,
  ease: "easeInOut",
};

export const smallMotions = [
  {
    position: "absolute",
    top: "10%",
    left: "5%",
    width: "12px",
    height: "12px",
    bg: "teal.300",
    opacity: 0.4,
    borderRadius: "full",
    zIndex: 0,
    animate: {
      x: [0, 15, -10, 0],
      y: [0, -20, 10, 0],
      transition: {
        duration: 12,
        repeat: Infinity,
        repeatType: "loop" as const,
        ease: "easeInOut",
      },
    },
  },
  {
    position: "absolute",
    top: "30%",
    left: "75%",
    width: "10px",
    height: "10px",
    bg: "blue.300",
    opacity: 0.3,
    borderRadius: "full",
    zIndex: 0,
    animate: {
      x: [0, -20, 15, 0],
      y: [0, 25, -10, 0],
      transition: {
        duration: 9,
        repeat: Infinity,
        repeatType: "loop" as const,
        ease: "easeInOut",
      },
    },
  },
  {
    position: "absolute",
    top: "50%",
    left: "20%",
    width: "15px",
    height: "15px",
    bg: "purple.300",
    opacity: 0.35,
    borderRadius: "full",
    zIndex: 0,
    animate: {
      x: [0, 10, -15, 0],
      y: [0, -15, 15, 0],
      transition: {
        duration: 10.5,
        repeat: Infinity,
        repeatType: "loop" as const,
        ease: "easeInOut",
      },
    },
  },
  {
    position: "absolute",
    top: "50%",
    left: "20%",
    width: "15px",
    height: "15px",
    bg: "purple.300",
    opacity: 0.35,
    borderRadius: "full",
    zIndex: 0,
    animate: {
      x: [0, 10, -15, 0],
      y: [0, -15, 15, 0],
      transition: {
        duration: 10.5,
        repeat: Infinity,
        repeatType: "loop" as const,
        ease: "easeInOut",
      },
    },
  },
  {
    position: "absolute",
    top: "50%",
    left: "20%",
    width: "15px",
    height: "15px",
    bg: "purple.300",
    opacity: 0.35,
    borderRadius: "full",
    zIndex: 0,
    animate: {
      x: [0, 10, -15, 0],
      y: [0, -15, 15, 0],
      transition: {
        duration: 10.5,
        repeat: Infinity,
        repeatType: "loop" as const,
        ease: "easeInOut",
      },
    },
  },
  {
    position: "absolute",
    top: "50%",
    left: "20%",
    width: "15px",
    height: "15px",
    bg: "purple.300",
    opacity: 0.35,
    borderRadius: "full",
    zIndex: 0,
    animate: {
      x: [0, 10, -15, 0],
      y: [0, -15, 15, 0],
      transition: {
        duration: 10.5,
        repeat: Infinity,
        repeatType: "loop" as const,
        ease: "easeInOut",
      },
    },
  },
  {
    position: "absolute",
    top: "50%",
    left: "20%",
    width: "15px",
    height: "15px",
    bg: "purple.300",
    opacity: 0.35,
    borderRadius: "full",
    zIndex: 0,
    animate: {
      x: [0, 10, -15, 0],
      y: [0, -15, 15, 0],
      transition: {
        duration: 10.5,
        repeat: Infinity,
        repeatType: "loop" as const,
        ease: "easeInOut",
      },
    },
  },

  {
    position: "absolute",
    top: "5%",
    left: "90%",
    width: "8px",
    height: "8px",
    bg: "cyan.400",
    opacity: 0.25,
    borderRadius: "full",
    zIndex: 0,
    animate: {
      x: [0, 5, -10, 0],
      y: [0, 10, -5, 0],
      transition: {
        duration: 8,
        repeat: Infinity,
        repeatType: "loop" as const,
        ease: "easeInOut",
      },
    },
  },
  {
    position: "absolute",
    top: "85%",
    left: "10%",
    width: "20px",
    height: "20px",
    bg: "pink.300",
    opacity: 0.4,
    borderRadius: "full",
    zIndex: 0,
    animate: {
      x: [0, 15, -5, 0],
      y: [0, -10, 20, 0],
      transition: {
        duration: 14,
        repeat: Infinity,
        repeatType: "loop" as const,
        ease: "easeInOut",
      },
    },
  },
  {
    position: "absolute",
    top: "60%",
    left: "65%",
    width: "10px",
    height: "10px",
    bg: "orange.300",
    opacity: 0.3,
    borderRadius: "full",
    zIndex: 0,
    animate: {
      x: [0, -12, 8, 0],
      y: [0, 15, -10, 0],
      transition: {
        duration: 11,
        repeat: Infinity,
        repeatType: "loop" as const,
        ease: "easeInOut",
      },
    },
  },
  {
    position: "absolute",
    top: "25%",
    left: "30%",
    width: "18px",
    height: "18px",
    bg: "green.200",
    opacity: 0.5,
    borderRadius: "full",
    zIndex: 0,
    animate: {
      x: [0, -10, 15, 0],
      y: [0, -20, 10, 0],
      transition: {
        duration: 13,
        repeat: Infinity,
        repeatType: "loop" as const,
        ease: "easeInOut",
      },
    },
  },
  {
    position: "absolute",
    top: "40%",
    left: "50%",
    width: "9px",
    height: "9px",
    bg: "yellow.200",
    opacity: 0.2,
    borderRadius: "full",
    zIndex: 0,
    animate: {
      x: [0, 12, -8, 0],
      y: [0, 10, -10, 0],
      transition: {
        duration: 9.5,
        repeat: Infinity,
        repeatType: "loop" as const,
        ease: "easeInOut",
      },
    },
  },
  {
    position: "absolute",
    top: "75%",
    left: "80%",
    width: "16px",
    height: "16px",
    bg: "red.200",
    opacity: 0.3,
    borderRadius: "full",
    zIndex: 0,
    animate: {
      x: [0, 18, -5, 0],
      y: [0, -15, 12, 0],
      transition: {
        duration: 12.5,
        repeat: Infinity,
        repeatType: "loop" as const,
        ease: "easeInOut",
      },
    },
  },
  {
    position: "absolute",
    top: "15%",
    left: "45%",
    width: "7px",
    height: "7px",
    bg: "blue.200",
    opacity: 0.15,
    borderRadius: "full",
    zIndex: 0,
    animate: {
      x: [0, -7, 7, 0],
      y: [0, 5, -5, 0],
      transition: {
        duration: 10,
        repeat: Infinity,
        repeatType: "loop" as const,
        ease: "easeInOut",
      },
    },
  },
  {
    position: "absolute",
    top: "90%",
    left: "50%",
    width: "22px",
    height: "22px",
    bg: "purple.100",
    opacity: 0.4,
    borderRadius: "full",
    zIndex: 0,
    animate: {
      x: [0, 20, -10, 0],
      y: [0, -5, 5, 0],
      transition: {
        duration: 15,
        repeat: Infinity,
        repeatType: "loop" as const,
        ease: "easeInOut",
      },
    },
  },
  {
    position: "absolute",
    top: "35%",
    left: "15%",
    width: "14px",
    height: "14px",
    bg: "lime.200",
    opacity: 0.3,
    borderRadius: "full",
    zIndex: 0,
    animate: {
      x: [0, -10, 15, 0],
      y: [0, 20, -10, 0],
      transition: {
        duration: 10.8,
        repeat: Infinity,
        repeatType: "loop" as const,
        ease: "easeInOut",
      },
    },
  },
  {
    position: "absolute",
    top: "65%",
    left: "40%",
    width: "11px",
    height: "11px",
    bg: "sky.300",
    opacity: 0.25,
    borderRadius: "full",
    zIndex: 0,
    animate: {
      x: [0, 14, -10, 0],
      y: [0, -15, 12, 0],
      transition: {
        duration: 13.2,
        repeat: Infinity,
        repeatType: "loop" as const,
        ease: "easeInOut",
      },
    },
  },
];
